### ISSUE TITLE
Readme Documentation

### ISSUE THREAD

**Issue by Jmeyer1292** [tesseract-robotics/trajopt#12]
I believe that there should be useful documentation on the front page of the README here. I see that there is some form of documentation available via the `gh_pages` directory, but that requires extra steps to build and so will be created by a _very_ small fraction of people.

This package has awesome capabilities and we should endeavor to make them as discoverable as possible. My suggestions:
 1. Create a README file on the front page that gives an overview, some pretty pictures, getting-started instructions, and maybe some code samples. See [examples](https://github.com/matiassingers/awesome-readme)
 2. Build and link to a static version of your Sphinx stuff.

**Comment by rjoomen** [comment]
I think this can be closed.
