### ISSUE TITLE
Optizelle Support

### ISSUE THREAD

**Issue by Jmeyer1292** [tesseract-robotics/trajopt#18]
I recently stumbled across [Optizelle](http://www.optimojoe.com/products/optizelle/) which appears to be an open-source (BSD) constrained optimizer that seems like a promising fit with this library. 

See their [github](http://www.optimojoe.com/products/optizelle/).

**Comment by arocchi** [comment]
I would suggest [OSQP](https://osqp.org/) and [qpOASES](https://projects.coin-or.org/qpOASES) as additional candidates.

**Comment by rjoomen** [comment]
This can be closed, as it has been added to the wish list.
