### ISSUE TITLE
rviz: /usr/include/OGRE/OgreAxisAlignedBox.h:696: Ogre::Vector3 Ogre::AxisAlignedBox::getCenter() const: Assertion `(mExtent == EXTENT_FINITE) && "Can't get center of a null or infinite AAB"' failed.

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/trajopt#294]
constraint violations: (1.05234e-30, 8.46866e-08, 4.13798e-08, 1.76573e-09, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
n func evals: 16
n qp solves: 15
==================
Debug:   Motion Planner process succeeded
Debug:   worker 4 finished running TRAJOPT
Debug:   worker 4 ready to run DISCRETE_CONTACT_CHECK
Debug:   Environment, getJointGroup(manipulator) cache hit!
Debug:   Discrete contact check succeeded
Debug:   worker 4 finished running DISCRETE_CONTACT_CHECK
Debug:   worker 4 ready to run ITERATIVE_SPLINE_PARAMETERIZATION
Debug:   Environment, getJointGroup(manipulator) cache hit!
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Profile 'DEFAULT' was not found in namespace 'ITERATIVE_SPLINE_PARAMETERIZATION' for type 'N18tesseract_planning38IterativeSplineParameterizationProfileE'. Using default if available. Available profiles:
Debug:   Iterative spline time parameterization succeeded
Debug:   worker 4 finished running ITERATIVE_SPLINE_PARAMETERIZATION
Debug:   worker 4 ready to run Done Callback
Info:    TrajOptTaskflow Successful: 
Debug:   worker 4 finished running Done Callback
**[ERROR] [1658832512.745020165]: Hit enter key to continue!
rviz: /usr/include/OGRE/OgreAxisAlignedBox.h:696: Ogre::Vector3 Ogre::AxisAlignedBox::getCenter() const: Assertion `(mExtent == EXTENT_FINITE) && "Can't get center of a null or infinite AAB"' failed.
[tesseract_ros_examples_pick_and_place_example_rviz-3] process has died [pid 128544, exit code -6, cmd /opt/ros/noetic/lib/rviz/rviz -d /home/test/ws_tesseract/src/tesseract_ros-0.5.1/tesseract_ros_examples/config/examples.rviz __name:=tesseract_ros_examples_pick_and_place_example_rviz __log:=/home/test/.ros/log/7afac986-0cd0-11ed-a5f9-d7b008ed318d/tesseract_ros_examples_pick_and_place_example_rviz-3.log].
log file: /home/test/.ros/log/7afac986-0cd0-11ed-a5f9-d7b008ed318d/tesseract_ros_examples_pick_and_place_example_rviz-3*.log**

**Comment by Levi-Armstrong** [comment]
This is the error which is an assert in Ogre. I will try running it on my machine, but you may also try searching the error and see if there is a know issue in Ogre/Rviz.
``` bash
rviz: /usr/include/OGRE/OgreAxisAlignedBox.h:696: Ogre::Vector3 Ogre::AxisAlignedBox::getCenter() const: Assertion `(mExtent == EXTENT_FINITE) && "Can't get center of a null or infinite AAB"' failed.
```
