### ISSUE TITLE
jsoncpp includes cause linking errors in tesseract_planning

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/trajopt#298]
The way jsoncpp is included in the CMake target_link_libraries causes a linking error in tesseract_planning on Ubuntu 22.04:
`/usr/bin/ld: cannot find -ljsoncpp_lib: No such file or directory`

**Comment by rjoomen** [comment]
For reference: open-source-parsers/jsoncpp#1356

**Comment by Levi-Armstrong** [comment]
Thanks for the fix.
