### ISSUE TITLE
How to visualize a trajectory in rViz?

### ISSUE THREAD

**Issue by allicen** [tesseract-robotics/trajopt#305]
When I run the example **roslaunch tesseract_ros_examples glass_upright_example.launch**, I only see a point cloud. And I can't start executing the TrajOpt trajectory in rViz:
![trajopt](https://user-images.githubusercontent.com/46901956/221375922-471ed3aa-87c8-4c16-a388-397b78bce9ca.png)
Any ideas how to do this? Thank you

**Comment by Levi-Armstrong** [comment]
What version are you using? In the tesseract panel it should have a trajectory tab which allows you to play, pause and select states.

**Comment by Levi-Armstrong** [comment]
https://github.com/tesseract-robotics/tesseract_qt/blob/main/docs/images/tesseract_qt_joint_trajectory_widget.png

**Comment by allicen** [comment]
Thanks! I use Ubuntu 20.04 + Ros Noetic + Docker.
This button is not visible in the default theme rViz:
![rviz-default](https://user-images.githubusercontent.com/46901956/221380922-716fe756-cc04-4597-99cb-3617571764a4.png)

I can't choose here. Do I need additional settings?
![rviz-manip](https://user-images.githubusercontent.com/46901956/221381035-1881f14d-720a-4533-b606-9231186ee1e9.png)

**Comment by Levi-Armstrong** [comment]
Hit the refresh button which is the last toolbar button. It grabs a snap shot of the kinematics objects since in Tesseract these can be changed.

**Comment by allicen** [comment]
Thanks, it works!
