### ISSUE TITLE
Naming of CollisionCoeffData::setPairCollisionMarginData()

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/trajopt#325]
I seems to me that [CollisionCoeffData::setPairCollisionMarginData()](https://github.com/tesseract-robotics/trajopt/blob/8066b980f35f245a68961b290d44cf1a46770ed2/trajopt_ifopt/src/constraints/collision/collision_types.cpp#L35) should be called CollisionCoeffData::setPairCollisionCoeff(), as it sets the coefficient instead of the margin (the getter is correctly called getPairCollisionCoeff()).

Should I submit a PR?

**Comment by Levi-Armstrong** [comment]
You are correct. Sure please do.

**Comment by rjoomen** [comment]
Same file: is [this line](https://github.com/tesseract-robotics/trajopt/blob/master/trajopt_ifopt/src/constraints/collision/collision_types.cpp#L9) still correct?

**Comment by Levi-Armstrong** [comment]
I would say that line can be removed

**Comment by rjoomen** [comment]
I removed it at a few more places, please review.
