### ISSUE TITLE
error: invalid initialization of reference of type ‘const string&’ {aka ‘const std::__cxx11::basic_string<char>&’} from expression of type ‘tesseract_common::LinkNamesPair’ {aka ‘std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >’}

### ISSUE THREAD

**Issue by Noah-Lau** [tesseract-robotics/trajopt#328]
###Description 
I cloned this repo to my workspace, then build this progect using `catkin build`. I got an error log as below:

![image](https://github.com/tesseract-robotics/trajopt/assets/75355347/d772b09f-ddf0-4f24-b5e8-2f83b324bd20)

### Your environment
* ROS Distro: Noetic
* OS Version: 20.04
* Source  build, master branch

Thank you in advance for any assistance or insights regarding this matter. I appreciate your time and expertise!

**Comment by Levi-Armstrong** [comment]
This should be address, please reopen if not.
