### ISSUE TITLE
Error: /trajopt/json_marshal.hpp:36:25: error: range-based ‘for’ expression of type ‘const Json::Value’ has incomplete type    36 |   for (const auto& it : parent)

### ISSUE THREAD

**Issue by Noah-Lau** [tesseract-robotics/trajopt#329]
###Description

When I compile the trajopt package, I got an error as below:
![image](https://github.com/tesseract-robotics/trajopt/assets/75355347/9033d2a2-1ff7-49c3-b977-3955ddf94414)

I have no idea what that mean.

###Your environment
ROS Distro: Noetic
OS Version: 20.04
Source build, master branch

How can I fix this bug ?

Thank you in advance for any assistance or insights regarding this matter. I appreciate your time and expertise!

**Comment by Noah-Lau** [comment]
@rjoomen

**Comment by rjoomen** [comment]
I'm not sure, a jsoncpp dependency/version problem maybe?

**Comment by Levi-Armstrong** [comment]
Closing because this appears to be using MoveIt's version.
