### ISSUE TITLE
cant understand how to scale the penalty coefficient in ”trajopt_optimizers/trajopt_sqp“.

### ISSUE THREAD

**Issue by sailuluo** [tesseract-robotics/trajopt#353]
in ”trajopt_optimizers\trajopt_sqp\src\trust_region_sqp_solver.cpp“，
It seems that it is necessary to update the constraint coefficient at the end of each loop through "TrustRegionSQPSolver::adjustPenalty()",
But I can only find updates of the SQP result，cant find updates of qp_problem.

**Comment by Levi-Armstrong** [comment]
This is a know issue, I believe this is one the final remaining items to tackle to where the Ifopt version aligns with the legacy. I have not had time to look into how best solve this. If you have any thoughts please let me know.

**Comment by Levi-Armstrong** [comment]
Addressed by #366
